server:
  port: 9001
dubbo:
  application:
    #注册到注册中心的名称
    name: consumer
  #采用协议和端口号
  protocol:
    #采用dubbo协议
    name: dubbo
    #发布dubbo端口号为20880
    port: 20881
  registry:
    #注册中心地址
    address: zookeeper://127.0.0.1:2181
  ##### 调用服务超时时间
  consumer:
    timeout: 5000
spring:
  output:
    ansi:
      enabled: always